/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../wrangler.jsonc --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: e152179252f5ef3cdfec988618f3bdd1)
interface __BaseEnv_CloudflareBindings {
	USAGE_DB: D1Database;
	ASSETS: Fetcher;
	SESSION_DO: DurableObjectNamespace<import("./index").SessionRelay>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "SessionRelay";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
