/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../wrangler.jsonc --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: d9ef0efc5a35891456da3553b103cb4e)
interface __BaseEnv_CloudflareBindings {
	ASSETS: Fetcher;
	SESSION_DO: DurableObjectNamespace<import("./index").SessionRelay>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "SessionRelay";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
